import JSZip from 'jszip';
import { jsPDF } from 'jspdf';
import { Student } from '../types';
import { UNIVERSAL_DOCS, COUNTRY_SPECIFIC_DOCS } from '../constants';

const getFileExtension = (filename: string): string => {
    return filename.slice((Math.max(0, filename.lastIndexOf(".")) || Infinity) + 1);
};

export const generatePartnerBundle = async (student: Student, agencyName: string) => {
    const zip = new JSZip();
    const folderName = `${student.name.replace(/\s+/g, '_')}_Application_Bundle`;
    const folder = zip.folder(folderName);

    if (!folder) throw new Error("Failed to create zip folder");

    // 1. GENERATE SUMMARY PDF
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.text("Student Profile Summary", 20, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated by ${agencyName} | Date: ${new Date().toLocaleDateString()}`, 20, 28);
    
    // Line separator
    doc.setDrawColor(200);
    doc.line(20, 32, 190, 32);

    // Profile Details
    doc.setTextColor(0);
    doc.setFontSize(12);
    let y = 45;

    const addRow = (label: string, value: string) => {
        doc.setFont("helvetica", "bold");
        doc.text(label, 20, y);
        doc.setFont("helvetica", "normal");
        doc.text(value || "N/A", 80, y);
        y += 10;
    };

    addRow("Full Name:", student.name);
    addRow("Date of Birth:", student.dateOfBirth || "N/A");
    addRow("Passport Number:", student.passportNumber || "N/A");
    addRow("Nationality:", student.nationality || "N/A");
    addRow("Email:", student.email);
    addRow("Phone:", student.phone);
    
    y += 5;
    doc.setFont("helvetica", "bold");
    doc.text("Academic & Test Scores", 20, y);
    y += 10;
    doc.setFont("helvetica", "normal");

    addRow("Target Country:", student.targetCountry);
    addRow("English Test:", `${student.testType || 'None'} (${student.testScore || 'Pending'})`);
    addRow("GPA / Marks:", student.gpa || "N/A");
    addRow("Education Gap:", `${student.educationGap || 0} Years`);

    // Add Branding Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text("This document is part of a secure application bundle. Confidential.", 20, 280);

    // Add PDF to Zip
    const pdfBlob = doc.output('blob');
    folder.file("00_Student_Summary.pdf", pdfBlob);

    // 2. PROCESS AND RENAME DOCUMENTS
    const allDocsRequirements = [...UNIVERSAL_DOCS, ...(COUNTRY_SPECIFIC_DOCS[student.targetCountry] || [])];

    if (student.documentFiles) {
        for (const [docName, fileData] of Object.entries(student.documentFiles)) {
            const fileUrl = typeof fileData === 'string' ? '' : fileData.url; 
            const originalName = typeof fileData === 'string' ? fileData : fileData.filename;
            
            if (!fileUrl) continue;

            try {
                const response = await fetch(fileUrl);
                const blob = await response.blob();
                const ext = getFileExtension(originalName) || 'pdf';
                const req = allDocsRequirements.find(d => d.name === docName);
                const category = req ? req.category : 'Doc';
                const cleanDocName = docName.replace(/[^a-zA-Z0-9]/g, '');
                const newFilename = `${category.toUpperCase()}_${cleanDocName}.${ext}`;

                folder.file(newFilename, blob);
            } catch (err) {
                console.error(`Failed to bundle ${docName}`, err);
            }
        }
    }

    // 3. GENERATE ZIP
    const content = await zip.generateAsync({ type: "blob" });
    return content;
};